menu:
  Home: /
  Archives: /archives
  Tags: /tags

# gitment
gitment: true
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId:
